### ISSUE TITLE
connection Error

### ISSUE THREAD

**Issue by nextel** [shelomentsevd/telegram-api#3]
Hi, in my opinion you have a bug right here https://github.com/shelomentsevd/mtproto/blob/master/mtproto.go#L137
because if  m.readData() != err, address in function signature didn't pass to m.addr field and if we trying  to  connect we get an error : missing port in address

**Comment by shelomentsevd** [comment]
Hi, thank you for your report! 
There is no bug, because m.readData gets address from session file [here](https://github.com/shelomentsevd/mtproto/blob/master/mtproto.go#L577).
But now I think this may be isn't convenient to establish connection with new server if we have session file from previous connection. In this case address just will be ignored.

**Comment by shelomentsevd** [comment]
I added "newSession" argument to function NewMTProto when it's true function doesn't check session file.
